### ISSUE TITLE
File "/home/qf/code/osp-main/projects/mmdet3d_plugin/bevformer/dense_heads/bevformer_occ_head.py", line 352, in forward     occ_score_cat = torch.cat(occ_score_list).cpu().numpy() NotImplementedError: 请问这个问题如何解决呀？

### ISSUE THREAD

**Issue by Hualin1995** [hustvl/osp#6]
2024-09-20 11:07:01,745 - root - INFO - ModulatedDeformConvPack img_backbone.layer4.2.conv2 is upgraded to version 2.
[                                                  ] 0/6019, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/test.py", line 274, in <module>
    main()
  File "./tools/test.py", line 241, in main
    outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir,
  File "/home/qf/code/osp-main/projects/mmdet3d_plugin/bevformer/apis/test.py", line 73, in custom_multi_gpu_test
    result = model(return_loss=False, rescale=True, **data)
  File "/home/qf/anaconda3/envs/vox/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qf/anaconda3/envs/vox/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/qf/anaconda3/envs/vox/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qf/code/osp-main/projects/mmdet3d_plugin/bevformer/detectors/bevformer_occ.py", line 158, in forward
    return self.forward_test(**kwargs)
  File "/home/qf/code/osp-main/projects/mmdet3d_plugin/bevformer/detectors/bevformer_occ.py", line 278, in forward_test
    occ_results = self.simple_test(
  File "/home/qf/code/osp-main/projects/mmdet3d_plugin/bevformer/detectors/bevformer_occ.py", line 306, in simple_test
    occ = self.simple_test_pts(
  File "/home/qf/code/osp-main/projects/mmdet3d_plugin/bevformer/detectors/bevformer_occ.py", line 292, in simple_test_pts
    outs = self.pts_bbox_head(x, img_metas,voxel_semantics= voxel_semantics, mask_camera=mask_camera, prev_bev=prev_bev, test=True)
  File "/home/qf/anaconda3/envs/vox/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/qf/anaconda3/envs/vox/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/qf/code/osp-main/projects/mmdet3d_plugin/bevformer/dense_heads/bevformer_occ_head.py", line 352, in forward
    occ_score_cat = torch.cat(occ_score_list).cpu().numpy()
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, UNKNOWN_TENSOR_TYPE_ID, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

**Comment by shawnsya** [comment]
看起来是传了一个空的list，我没遇到过这个问题，你可以断点调试一下。

**Comment by Hualin1995** [comment]
我已经收到您发给我的邮件，看到后我会尽快查看并进行相应的回复，谢谢。
                    ——陈华林
